### ISSUE TITLE
Why reference to old System.Net.Http net40?

### ISSUE THREAD

**Issue by jenokizm** [lilpug/dotnetaes#1]
```
 <Reference Include="System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\DotNetAES.1.0.1\lib\net4\System.Net.Http.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

but my project use 2.2.29.0. The library replaced the old one and why do you turn it on?

**Comment by jenokizm** [comment]
If you need this dependency, it would be right to make it a link to the nugget package. Then it would be possible to update the dependency or at least explicitly track its presence.
https://www.nuget.org/packages/Microsoft.Net.Http/

**Comment by lilpug** [comment]
Hi, this was done quite sometime ago, i can look to reference the NuGet package as a dependency when i get some time but i would just recommend putting a web.config runtime redirect binding in your config for now as this would resolve the issue.

**Comment by lilpug** [comment]
An example:-
``
<dependentAssembly>
  <assemblyIdentity name="someAssembly" publicKeyToken="32ab4ba45e0a69a1" culture="en-us" />
  <bindingRedirect oldVersion="7.0.0.0" newVersion="8.0.0.0" />
</dependentAssembly>
``

**Comment by lilpug** [comment]
This has now been resolved, i have restructure the project to be .NET Standard so both framework and core can use it along with the correct NuGet references.
